theme: jekyll-theme-minimal

name: Akhil Gupta
bio: 'A Man who travels the world eating noodles'
picture: 
...

and lot of other options, like width, projects, pages, read-time, tags, related posts, animations, multiple-authors, etc.
