theme: jekyll-theme-minimal

name: Akhil Gupta
bio: Data Science @ CRED. Interested in research opportunities, experience in ML Research.

...

and lot of other options, like width, projects, pages, read-time, tags, related posts, animations, multiple-authors, etc.
